# Actividad 4.1

In [4]:
import pandas as pd
import numpy as np

# Crear un dataframe valores nulos
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', None],
    'Edad': [23, np.nan, 35, 29],
    'Ciudad': ['CDMX', 'Guadalajara', None, 'Monterrey']
}


df = pd.DataFrame(data)
display(df)
display(df.isnull())
display(df.notnull())

print(df.isnull().sum())

df.info()

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis   NaN  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

   Nombre   Edad  Ciudad
0   False  False   False
1   False   True   False
2   False  False    True
3    True  False   False

   Nombre   Edad  Ciudad
0    True   True    True
1    True  False    True
2    True   True   False
3   False   True    True

Nombre    1
Edad      1
Ciudad    1
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      str
 1   Edad    3 non-null      float64
 2   Ciudad  3 non-null      str
dtypes: float64(1), str(2)
memory usage: 228.0 bytes

# Actividad 4.2

In [6]:
# Crear un dataframe valores nulos
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', None],
    'Edad': [23, np.nan, 35, 29],
    'Ciudad': ['CDMX', 'Guadalajara', None, 'Monterrey']
}


df = pd.DataFrame(data)
display(df)

df_media = df.copy()
df_media['Edad'] = df_media['Edad'].fillna(df_media['Edad'].mean())

print("Imputación por media:")
display(df_media)

df_mediana = df.copy()
df_mediana['Edad'] = df_mediana['Edad'].fillna(df_mediana['Edad'].median())

print("Imputación por mediana:")
display(df_mediana)

df_moda = df.copy()

df_moda['Edad'] = df_moda['Edad'].fillna(df_moda['Edad'].mode()[0])
df_moda['Ciudad'] = df_moda['Ciudad'].fillna(df_moda['Ciudad'].mode()[0])
df_moda['Nombre'] = df_moda['Nombre'].fillna(df_moda['Nombre'].mode()[0])

print("Imputación por moda:")
display(df_moda)

df_ffill = df.ffill()
print("Forward fill:")
display(df_ffill)

df_bfill = df.bfill()
print("Backward fill:")
display(df_bfill)

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis   NaN  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por media:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  29.0  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por mediana:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  29.0  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por moda:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  23.0  Guadalajara
2  Carlos  35.0         CDMX
3     Ana  29.0    Monterrey

Forward fill:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  23.0  Guadalajara
2  Carlos  35.0  Guadalajara
3  Carlos  29.0    Monterrey

Backward fill:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  35.0  Guadalajara
2  Carlos  35.0    Monterrey
3     NaN  29.0    Monterrey

## ¿Cuándo usar cada uno?
- Media
    - Cuando los datos son numéricos y simétricos

- Mediana
    - Cuando hay outliers (valores extremos)

- Moda
    - Para datos categóricos

- Forward / Backward Fill
    - Cuando hay orden temporal o secuencia