# Actividad 4.1

In [4]:
import pandas as pd
import numpy as np

# Crear un dataframe valores nulos
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', None],
    'Edad': [23, np.nan, 35, 29],
    'Ciudad': ['CDMX', 'Guadalajara', None, 'Monterrey']
}


df = pd.DataFrame(data)
display(df)
display(df.isnull())
display(df.notnull())

print(df.isnull().sum())

df.info()

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis   NaN  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

   Nombre   Edad  Ciudad
0   False  False   False
1   False   True   False
2   False  False    True
3    True  False   False

   Nombre   Edad  Ciudad
0    True   True    True
1    True  False    True
2    True   True   False
3   False   True    True

Nombre    1
Edad      1
Ciudad    1
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      str
 1   Edad    3 non-null      float64
 2   Ciudad  3 non-null      str
dtypes: float64(1), str(2)
memory usage: 228.0 bytes

# Actividad 4.2

In [6]:
# Crear un dataframe valores nulos
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', None],
    'Edad': [23, np.nan, 35, 29],
    'Ciudad': ['CDMX', 'Guadalajara', None, 'Monterrey']
}


df = pd.DataFrame(data)
display(df)

df_media = df.copy()
df_media['Edad'] = df_media['Edad'].fillna(df_media['Edad'].mean())

print("Imputación por media:")
display(df_media)

df_mediana = df.copy()
df_mediana['Edad'] = df_mediana['Edad'].fillna(df_mediana['Edad'].median())

print("Imputación por mediana:")
display(df_mediana)

df_moda = df.copy()

df_moda['Edad'] = df_moda['Edad'].fillna(df_moda['Edad'].mode()[0])
df_moda['Ciudad'] = df_moda['Ciudad'].fillna(df_moda['Ciudad'].mode()[0])
df_moda['Nombre'] = df_moda['Nombre'].fillna(df_moda['Nombre'].mode()[0])

print("Imputación por moda:")
display(df_moda)

df_ffill = df.ffill()
print("Forward fill:")
display(df_ffill)

df_bfill = df.bfill()
print("Backward fill:")
display(df_bfill)

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis   NaN  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por media:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  29.0  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por mediana:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  29.0  Guadalajara
2  Carlos  35.0          NaN
3     NaN  29.0    Monterrey

Imputación por moda:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  23.0  Guadalajara
2  Carlos  35.0         CDMX
3     Ana  29.0    Monterrey

Forward fill:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  23.0  Guadalajara
2  Carlos  35.0  Guadalajara
3  Carlos  29.0    Monterrey

Backward fill:

   Nombre  Edad       Ciudad
0     Ana  23.0         CDMX
1    Luis  35.0  Guadalajara
2  Carlos  35.0    Monterrey
3     NaN  29.0    Monterrey

## ¿Cuándo usar cada uno?
- Media
    - Cuando los datos son numéricos y simétricos

- Mediana
    - Cuando hay outliers (valores extremos)

- Moda
    - Para datos categóricos

- Forward / Backward Fill
    - Cuando hay orden temporal o secuencia

# Actividad 4.3

In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sofía'],
    'Edad': [23, 45, 35, 29],
    'Salario': [10000, 20000, 15000, 12000],
    'Ciudad': ['CDMX', 'Guadalajara', 'Monterrey', 'CDMX']
}

df = pd.DataFrame(data)
display(df)

scaler = MinMaxScaler()

df_minmax = df.copy()
df_minmax[['Edad', 'Salario']] = scaler.fit_transform(df[['Edad', 'Salario']])

print("Normalización Min-Max:")
display(df_minmax)

scaler = StandardScaler()

df_std = df.copy()
df_std[['Edad', 'Salario']] = scaler.fit_transform(df[['Edad', 'Salario']])

print("Estandarización:")
display(df_std)

df_ohe = pd.get_dummies(df, columns=['Ciudad'])

print("One-Hot Encoding:")
display(df_ohe)

df_derivado = df.copy()

df_derivado['Salario_Anual'] = df_derivado['Salario'] * 12

print("Variables derivadas:")
display(df_derivado)

   Nombre  Edad  Salario       Ciudad
0     Ana    23    10000         CDMX
1    Luis    45    20000  Guadalajara
2  Carlos    35    15000    Monterrey
3   Sofía    29    12000         CDMX

Normalización Min-Max:

   Nombre      Edad  Salario       Ciudad
0     Ana  0.000000      0.0         CDMX
1    Luis  1.000000      1.0  Guadalajara
2  Carlos  0.545455      0.5    Monterrey
3   Sofía  0.272727      0.2         CDMX

Estandarización:

   Nombre      Edad   Salario       Ciudad
0     Ana -1.230915 -1.128330         CDMX
1    Luis  1.477098  1.526564  Guadalajara
2  Carlos  0.246183  0.199117    Monterrey
3   Sofía -0.492366 -0.597351         CDMX

One-Hot Encoding:

   Nombre  Edad  Salario  Ciudad_CDMX  Ciudad_Guadalajara  Ciudad_Monterrey
0     Ana    23    10000         True               False             False
1    Luis    45    20000        False                True             False
2  Carlos    35    15000        False               False              True
3   Sofía    29    12000         True               False             False

Variables derivadas:

   Nombre  Edad  Salario       Ciudad  Salario_Anual
0     Ana    23    10000         CDMX         120000
1    Luis    45    20000  Guadalajara         240000
2  Carlos    35    15000    Monterrey         180000
3   Sofía    29    12000         CDMX         144000

## Usos 
- MinMax
    - Datos en rango fijo
- ZScore
    - Datos con outliers (datos atipicos)
- One-Hot
    - Variables no numéricas
- Derivadas
    - Mejorar la información

# Actividad 4.4

In [15]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_selection import SelectKBest, f_classif

# Carga de datos
df = pd.DataFrame({
    "edad": [25, 30, np.nan, 35],
    "salario": [5000, 6000, 5500, np.nan],
    "departamento": ["IT", "HR", np.nan, "Ventas"],
    "target": [1, 0, 1, 0]
})

X = df.drop("target", axis=1)
y = df["target"]

# Columnas
num_cols = ["edad", "salario"]
cat_cols = ["departamento"]

# Pipeline
pipeline = Pipeline([
    ("preprocessing", ColumnTransformer([
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="mean")),
            ("scaler", StandardScaler())
        ]), num_cols),
        
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder())
        ]), cat_cols)
    ])),
    
    ("feature_selection", SelectKBest(score_func=f_classif, k=2))
])

X_procesado = pipeline.fit_transform(X, y)

display(X_procesado)

array([[-1.41421356, -1.41421356],
       [ 0.        ,  1.41421356],
       [ 0.        ,  0.        ],
       [ 1.41421356,  0.        ]])