# Procesamiento de Datos en Python

**Entorno:** `myenv` (numpy, pandas, ipykernel)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 1. map y filter

In [2]:
# map(): Duplicar numeros usando funcion y lambda
def duplicar(x):
    return x * 2

numeros = [1, 2, 3, 4, 5]

resultado_funcion = map(duplicar, numeros)
print(list(resultado_funcion))
#------------------
resultado_lambda = map(lambda x: x * 2, numeros)
print(list(resultado_lambda))
# Completar con map(duplicar, numeros) y map(lambda x: x*2, numeros)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]

In [3]:
# filter(): Obtener numeros pares e impares

def es_par(i):
    return i % 2 == 0

def es_impar(i):
    return i % 2 != 0

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pares = filter(es_par, numeros)
impares = filter(es_impar, numeros)

print(list(pares))
print(list(impares))
# Completar con filter para obtener pares e impares

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]

In [4]:
# Combinar map y filter: Celsius a Fahrenheit y filtrar > 80
def farenheit(i):
    return (i * 9/5) + 32
celsius = [10, 25, 30, 15, 35, 40]

temp_farenheit = map(farenheit, celsius)
print(list(temp_farenheit))

# Completar: map para convertir a F, filter para > 80

[50.0, 77.0, 86.0, 59.0, 95.0, 104.0]

## 2. Lambda

In [ ]:
# Lambda basicas: cuadrado, suma, maximo
# Completar: cuadrado = lambda ... ; suma = lambda ... ; maximo = lambda ...
cuadrado = lambda x: x ** 2
suma = lambda x, y: x + y
maximo = lambda x, y: x if x > y else y
print(cuadrado(5))
print(suma(3, 4))
print(maximo(10, 20))

In [ ]:
# sorted() con lambda: ordenar por edad y por nombre (desc)
personas = [("Ana", 25), ("Carlos", 30), ("Beatriz", 22)]
# Completar: sorted(personas, key=...)
orden_edad = sorted(personas, key=lambda x: x[1])
orden_nombre_desc = sorted(personas, key=lambda x: x[0], reverse=True)
print("Orden por edad:", orden_edad)
print("Orden por nombre (desc):", orden_nombre_desc)

In [ ]:
# max() y min() con lambda: mayor y menor edad
personas = [{"nombre": "Ana", "edad": 25}, {"nombre": "Carlos", "edad": 30}]
# Completar: max(..., key=...), min(..., key=...)
mayor_edad = max(personas, key=lambda x: x["edad"])
menor_edad = min(personas, key=lambda x: x["edad"])
print("Mayor edad:", mayor_edad)
print("Menor edad:", menor_edad)

## 3. NumPy

In [8]:
# Sin NumPy: suma con bucle for
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
# Completar: bucle for para sumar elementos
suma = []
for i in range(len(a)):
    suma.append(a[i] + b[i])
print(suma)

[11, 22, 33, 44, 55]

In [9]:
import numpy as np
# Con NumPy: operaciones +, -, *, /
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)  
print(a - b)  
print(a * b)  
print(b / a)  
# Completar: a+b, a-b, a*b, b/a

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]

In [10]:
# Funciones NumPy: sqrt, mean, std, median
a = np.array([1, 2, 3, 4, 5])
# Completar: np.sqrt(a), np.mean(a), np.std(a), np.median(a)

## 4. Limpieza de Datos

In [23]:
import pandas as pd
# Crear DataFrame con valores nulos
data = {'nombre': ['Juan', 'Maria', None, 'Ana'], 'edad': [25, None, 30, 40], 'salario': [50000, None, 48000, 12000]}
df = pd.DataFrame(data)
display(df)
display(df.info)

  nombre  edad  salario
0   Juan  25.0  50000.0
1  Maria   NaN      NaN
2    NaN  30.0  48000.0
3    Ana  40.0  12000.0

<bound method DataFrame.info of   nombre  edad  salario
0   Juan  25.0  50000.0
1  Maria   NaN      NaN
2    NaN  30.0  48000.0
3    Ana  40.0  12000.0>

In [44]:
# Deteccion de nulos: isnull().sum()
# Completar: df.isnull().sum()
data = {'nombre': ['Juan', 'Maria', None, 'Ana'], 'edad': [25, None, 30, 40], 'salario': [50000, None, 48000, 12000]}
df = pd.DataFrame(data)
df.isnull().sum()

nombre     1
edad       1
salario    1
dtype: int64

In [117]:
# Estrategias: dropna() y fillna()
# Completar: df.dropna() y df.fillna(valor)
data = {'nombre': ['Juan', 'Maria', None, 'Ana'], 'edad': [25, None, 30, 40], 'salario': [50000, None, 48000, 12000]}
df = pd.DataFrame(data)
df_limpio = df.copy()  
df_limpio.dropna()
display(df_limpio)
df_lleno = df.copy()
df_lleno["edad"]= df_lleno["edad"].fillna(df["edad"].median())
df_lleno["salario"]= df_lleno["salario"].fillna(df["salario"].median())
df_lleno["nombre"]= df_lleno["nombre"].fillna("Desconocido")
display(df_lleno)

  nombre  edad  salario
0   Juan  25.0  50000.0
1  Maria   NaN      NaN
2    NaN  30.0  48000.0
3    Ana  40.0  12000.0

        nombre  edad  salario
0         Juan  25.0  50000.0
1        Maria  30.0  48000.0
2  Desconocido  30.0  48000.0
3          Ana  40.0  12000.0

In [134]:
# Correccion de tipos: pd.to_numeric(..., errors='coerce')
df = pd.DataFrame({'edad': [25, 'desconocida', 30]})
data = {'nombre': ['Juan', 'Maria', None, 'Ana', 'Erick'], 'edad': [25, None, 30, 40,19], 'salario': [50000, None, 48000, 12000,18000], 'evaluacion': [8, 9, 7, 6, 10]}
df = pd.DataFrame(data)
# Completar: convertir columna edad a numerico
df_limpio = df.copy()
df_limpio['edad'] = pd.to_numeric(df['edad'], errors='coerce')
display(df_limpio)

  nombre  edad  salario  evaluacion
0   Juan  25.0  50000.0           8
1  Maria   NaN      NaN           9
2    NaN  30.0  48000.0           7
3    Ana  40.0  12000.0           6
4  Erick  19.0  18000.0          10

## 5. Reindexacion

In [149]:
# reindex() con fill_value
data = {
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]

}
df = pd.DataFrame(data, index=['a', 'b', 'c'])
display(df)
df_reindex = df.reindex(['a', 'b', 'c', 'd'], fill_value=0)
display(df_reindex)
# Completar: serie.reindex(['a','b','c','d'], fill_value=0)

   a  b  c
a  1  4  7
b  2  5  8
c  3  6  9

   a  b  c
a  1  4  7
b  2  5  8
c  3  6  9
d  0  0  0

In [150]:
# reindex en DataFrame: filas y columnas
df = pd.DataFrame({'col1': [1,2,3], 'col2': [4,5,6]}, index=['x','y','z'])
# Completar: df.reindex(['x','y','z','w']) y df.reindex(columns=[...], fill_value=0)

In [151]:
# ffill() y bfill()
serie = pd.Series([100, None, 300, None, 500])
# Completar: serie.ffill() y serie.bfill()

## 6. apply()

In [161]:
# apply() basic: suma por columna
def farenheit(i):
    return (i * 9/5) + 32
celsius = {'celsius': [10, 25, 30, 15, 35, 40]}
df = pd.DataFrame(celsius)

df['farenheit'] = df['celsius'].apply(farenheit)
display(df)
# Completar: df.apply(sum)

   celsius  farenheit
0       10       50.0
1       25       77.0
2       30       86.0
3       15       59.0
4       35       95.0
5       40      104.0

In [ ]:
# apply() con axis: axis=0 (columnas), axis=1 (filas)
# Completar: df.apply(max, axis=0) y df.apply(sum, axis=1)
def indice_corporal(row):
    peso = row['peso']
    altura = row['altura']
    itw = peso / (altura ** 2)
    return itw  

data = {
    'peso': [70, 80, 90,77,56,60],
    'altura': [1.75, 1.80, 1.85,1.70,1.60,1.65]

}
df = pd.DataFrame(data)
display(df)

In [163]:
# apply() con columnas: calcular IMC
df = pd.DataFrame({'peso': [70, 65], 'altura': [1.70, 1.60]})
# Completar: def imc(fila): return... ; df['imc'] = df.apply(..., axis=1)

In [164]:
# apply() para clasificacion (ej: IMC normal/sobrepeso)
df['categoria'] = df['imc'].apply(lambda x: 'Normal' if x < 25 else 'Sobrepeso')
# Completar: funcion con if/elif/else

KeyError: 'imc'

## 7. Merges

In [ ]:
# DataFrames para merge
# DataFrame de empleados
empleados = pd.DataFrame({'id_empleado': [1, 2, 3, 4],'nombre': ['Juan', 'Maria', 'Pedro', 'Ana'],'departamento_id': [10, 20, 10, 30]})

# DataFrame de departamentos
departamentos = pd.DataFrame({'departamento_id': [10, 20, 30], 'nombre_dept': ['TI', 'Ventas', 'RH']})

In [ ]:
# INNER JOIN: solo claves en ambas tablas
# Completar: pd.merge(empleados, departamentos, on='dept_id', how='inner')

In [ ]:
# LEFT JOIN: todos de empleados
# Completar: how='left'

In [ ]:
# RIGHT JOIN: todos de departamentos
# Completar: how='right'

In [ ]:
# OUTER JOIN: todos de ambas
# Completar: how='outer'

In [ ]:
# Merge con claves diferentes: left_on, right_on
df1 = pd.DataFrame({'id': [1,2], 'nombre': ['Juan','Maria']})
df2 = pd.DataFrame({'emp_id': [1,3], 'salario': [50000,60000]})
# Completar: pd.merge(df1, df2, left_on='id', right_on='emp_id', how='inner')

In [ ]:
# Merge multiple: encadenar merge()
# Completar: df1.merge(df2, on='...').merge(df3, on='...')

---
## Ejercicios

In [ ]:
# 1. temps = [15,22,30,18,25] -> Fahrenheit y filtrar >20

In [ ]:
# 2. personas = [{'nombre':'Ana','edad':25},{'nombre':'Carlos','edad':30}] -> ordenar por edad, max

In [ ]:
# 3. NumPy: a=np.array([1,2,3,4,5]), b=np.array([10,20,30,40,50]) -> +,-,*,/ y media,std

In [ ]:
# 4. df con nulos -> dropna, fillna, ffill

In [ ]:
# 5. serie.reindex(['a','b','c','d'], fill_value=0), ffill, bfill

In [ ]:
# 6. df(precio,cantidad) -> apply(lambda x: x['precio']*x['cantidad'], axis=1)

In [ ]:
# 7. df1,df2 -> inner, left, right, outer